notes/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, search

app_name = 'notes'
urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('post/new/', PostCreateView.as_view(), name='post-new'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/edit/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/search/', search, name='post-search'),
]

sticky_notes/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),
    path('', include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from .views import register, profile
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

user_pattern = ([
                    path('register/', register, name='register'),
                    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
                    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
                    path('profile/', profile, name='profile'),
                ], 'user')

urlpatterns = [
    path('user/', include(user_pattern, namespace='user')),
    # path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('login/', RedirectView.as_view(pattern_name='user:login'), name='login'),

    # password reset..
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

notes/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('notes:post-detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

notes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from .models import Post


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'notes/post_list.html'

    def get_queryset(self):
        # todo add empty list for new user
        user = get_object_or_404(User, username=self.request.user)
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Post
    template_name = 'notes/post_detail.html'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'description']
    extra_context = {'heading': 'New Note'}

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'description']
    extra_context = {'heading': 'Edit Note'}

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def search(request):
    query = request.GET.get('q')
    if query:
        queryset = ((Q(title__icontains=query)) | (Q(description__icontains=query))) & (Q(author=request.user))
        results = Post.objects.filter(queryset).distinct()
    else:
        results = []
    return render(request, 'notes/post_list.html', {'object_list': results, 'query': query})

users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.shortcuts import render, redirect


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your account has been created! You can now login')
            return redirect('user:login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!!')
            return redirect('user:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'users/profile.html', context)

templates/notes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Sticky Notes</title>
</head>
<body>
<header>
    {% include 'notes/nav.html' %}
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock %}
        </div>
    </div>
</main>
<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/notes/home.html
{% extends 'notes/base.html' %}

{% block content %}
    {% if query %}
        <h1 class="border-bottom">Search for '{{ query }}'</h1>
    {% endif %}
    <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 mt-4">
        {% for object in object_list %}
            <div class="col mb-4">
                <div class="card">
                    {#                    <img src="..." class="card-img-top" alt="...">#}
                    <a class="text-dark bg-light text-decoration-none " href="{% url 'notes:post-detail' object.id %}">
                        <div class="card-body">
                            {% if object.title %}
                                <h5 class="card-title">{{ object.title }}</h5>
                                <hr>
                            {% endif %}
                            <p class="small text-muted align-right"><em>{{ object.date_posted }}</em></p>
                            <p class="card-text">{{ object.description }}</p>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/notes/nav.html
<nav class="navbar navbar-expand-md navbar-light bg-light">
    {#    <a class="navbar-brand" href="{% url 'notes:post-list' %}">Notes</a>#}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler1" aria-controls="navbarToggler1"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarToggler1">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'notes:post-list' %}">Notes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Bar2</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'notes:post-new' %}">New<span class="sr-only">(current)</span></a>
            </li>
        </ul>


        <ul class="navbar-nav mt-2 mt-lg-0">
            {% if user.is_authenticated %}
                <form class="form-inline my-2 mx-4 m-lg-0" action="{% url 'notes:post-search' %}" method="get">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q">
                    <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
                </form>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
{#                        <img src="http://placehold.it/40x40" class="rounded-circle">#}
                        <img src="{{ user.profile.image.url }}" class="rounded-circle" style="width:35px;height:35px;">
                        {{ user.username|upper }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'password_reset' %}">Reset Password</a>
                        <a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>

</nav>

templates/notes/post_confirm_delete.html
{% extends 'notes/base.html' %}
{% block content %}
    <h1 class="border-bottom">Delete Post</h1>
    <div class="card my-4 p-4">
        <form method="post">
            {% csrf_token %}
            <h2>Confirm Delete</h2>
            <div class="mt-4">
                <p>{{ object.title }}</p>
                <button class="btn btn-outline-danger my-4" type="submit">Delete</button>
                <a class="btn btn-outline-info" href="../">Cancel</a>
            </div>
        </form>

    </div>
{% endblock %}

templates/notes/post_detail.html
{% extends 'notes/base.html' %}

{% block content %}
    <div class="row ">
        <div class="col mb-4">
            <div class="card">
                {#                    <img src="..." class="card-img-top" alt="...">#}
                <div class="card-body">
                    <h2 class="card-title">{{ object.title }}</h2>
                    <p class="small text-muted align-right">{{ object.date_posted }}</p>
                    <p class="card-text my-4 py-4">{{ object.description }}</p>
                </div>
            </div>
            <div class="justify-content-center">
                <a class="btn btn-outline-info" href="../../">Back</a>
                <a class="btn btn-outline-info" href="{% url 'notes:post-update' object.id %}">Edit</a>
                <a class="btn btn-outline-danger" href="{% url 'notes:post-delete' object.id %}">Delete</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/notes/post_form.html
{% extends 'notes/base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    {% if heading %}
        <h1 class="border-bottom">{{ heading }}</h1>
    {% endif %}
    <div class="card my-4 p-4">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div>
                <button class="btn btn-outline-info" type="submit">Save</button>
            </div>
        </form>

    </div>
{% endblock %}

templates/notes/post_list.html
{% extends 'notes/base.html' %}

{% block content %}
    {% if query %}
        <h1 class="border-bottom">Search for '{{ query }}'</h1>
    {% endif %}
    <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 mt-4">
        {% for object in object_list %}
            <div class="col mb-4">
                <div class="card">
                    {#                    <img src="..." class="card-img-top" alt="...">#}
                    <a class="text-dark bg-light text-decoration-none " href="{% url 'notes:post-detail' object.id %}">
                        <div class="card-body">
                            {% if object.title %}
                                <h5 class="card-title">{{ object.title }}</h5>
                                <hr>
                            {% endif %}
                            <p class="small text-muted align-right"><em>{{ object.date_posted }}</em></p>
                            <p class="card-text">{{ object.description }}</p>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/users/login.html
{% extends 'notes/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <h1 class="border-bottom pb-3">Log In</h1>
                <div class="pt-4">
                    {{ form|crispy }}
                </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'user:register' %}">Sign Up</a>
            </small>
        </div>
    </div>
{% endblock %}

templates/users/logout.html
{% extends 'notes/base.html' %}
{% block content %}
    <h1>You have been logged out</h1>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'user:login' %}">Log In Again</a>
        </small>
    </div>
{% endblock %}

templates/users/password_reset.html
{% extends 'notes/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/users/password_reset_complete.html
{% extends 'notes/base.html' %}
{% block content %}
    <div class="alert alert-info">
        Your password has been reset
    </div>
    <a href="{% url 'login' %}">Sign In Here</a>
{% endblock content %}

templates/users/password_reset_confirm.html
{% extends 'notes/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/users/password_reset_done.html
{% extends 'notes/base.html' %}
{% block content %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>
{% endblock content %}

templates/users/profile.html
{% extends 'notes/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="card my-4">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <img src="{{ user.profile.image.url }}" class="rounded-circle card-img-side float-left mr-4" style="width:100px;height:100px;">
                    <div>
                        <h1 class="card-title ">{{ user.username }}</h1>
                        <p>{{ user.email }}</p>
                    </div>
                </div>
            </div>
            <p class="card-text">{{ object.content }}</p>
        </div>
    </div>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h1 class="border-bottom">Profile Info</h1>
            {{ u_form|crispy }}
            {{ p_form|crispy }}
            <button class="btn btn-primary" type="submit">Update</button>
        </form>
    </div>
{% endblock %}

templates/users/register.html
{% extends 'notes/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <h1 class="border-bottom pb-3">Join Today</h1>
                <div class="pt-4">
                    {{ form|crispy }}
                </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign UP</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'user:login' %}">Sign In</a>
            </small>

        </div>
    </div>
{% endblock %}